name:                FinanceDSL
version:             0.1.0.0
github:              "pomarola/FinanceDSL"
license:             BSD-3-Clause
author:              "Lucas Poma"
maintainer:          "example@example.com"
copyright:           "2024 Lucas Poma"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pomarola/FinanceDSL#readme>

dependencies:
- base >= 4.7 && < 5
- array
- haskeline >= 0.8.0.0
- mtl
- exceptions
- QuickCheck
- containers
- prettyprinter
- prettyprinter-ansi-terminal
- extra
- text
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- GADTs
- StandaloneDeriving
- PatternSynonyms
- FlexibleInstances
- FlexibleContexts
- TupleSections
- MultiWayIf

library:
  source-dirs: src

executables:
  FinanceDSL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FinanceDSL
    build-tools:
    - happy

tests:
  FinanceDSL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FinanceDSL
